### PR TITLE
Optimized code performance

### PR DESCRIPTION
**Pull request by henrythierrydev**
I made some code updates to get better performance on the server.

Changes:

1. added strict types to all parameters and functions.

2. use of VanillaItems class constants instead of creating new objects at each check.

3. changed string equality check with === operator instead of ==.

4. optimized loading of plugin settings using the getConfig() and getDescription()->getVersion() methods instead of creating unnecessary temporary variables.

5. using a switch instead of several cascaded if statements to check if the item is soup.

6. added a return right after sending the message to the player that their health is already full, to avoid unnecessary code processing.

❤

### CODE REVIEW

**Comment by Henry8K** [comment]
hey, to fix the air, use 

$player->getInventory()->setItemInHand(VanillaBlocks::AIR()->asItem());

I ended up forgetting it existed, but remember when the other guy created a pull request lol

**Comment by henrythierrydev** [comment]
hey, to fix the air, use 

$player->getInventory()->setItemInHand(VanillaBlocks::AIR()->asItem());

I ended up forgetting it existed, but I remembered when the other guy created a pull request lol XD

**Comment by AshiePleb** [comment]
Thank you for your contribution! This will be merged in with the next update!

**Comment by henrythierrydev** [comment]
you're welcome

**Pull request merged**
